### ISSUE TITLE
apt-get step fails?

### ISSUE THREAD

**Issue by RogueM** [pimoroni/pimstaller#1]
here is what I get on a fully updated Wheezy. Seems the apt-get python3-smbus python-pip fail? I can install them manually but I thought you might want to react first... I'm going to jump on my clean Jessie and see what happens there.

pi@Rpi2 ~/Hub/pimstaller $ pimstaller display-o-tron
Welcome to Pimstaller, a Raspberry Pi add-on installer.
Version 1.0
Created by Pimoroni, contribute at http://github.com/pimoroni/pimstaller

Reading https://raw.githubusercontent.com/Gadgetoid/Pinout2/master/src/en-GB/overlay/display-o-tron.md

Found board Display-o-Tron 3000
    Description: A 3-line character LCD with an RGB backlight and joystick
    Manufacturer: Pimoroni
    Github: https://github.com/pimoroni/dot3k
    Url: https://github.com/pimoroni/dot3k

Install data found. Installing...
Checking for apt packages...
    python-smbus: Found!
    python3-smbus: Not found!
    python-dev: Found!
    python3-dev: Found!
    python-pip: Not found!

Installing apt packages...
    sudo apt-get --force-yes --yes install python3-smbus python-pip
    Unable to locate: python3-smbus
    Unable to locate: python-pip

Checking for Python 2 packages...
    dot3k: Found!

Installing examples from https://github.com/pimoroni/dot3k
    Find examples in ~/Pimoroni/dot3k

Done!

**Comment by RogueM** [comment]
strange, on a vanilla Jessie it worked:

pi@RpiB ~/Hub/pimstaller $ pimstaller display-o-tron
Welcome to Pimstaller, a Raspberry Pi add-on installer.
Version 1.0
Created by Pimoroni, contribute at http://github.com/pimoroni/pimstaller

Reading https://raw.githubusercontent.com/Gadgetoid/Pinout2/master/src/en-GB/overlay/display-o-tron.md

Found board Display-o-Tron 3000
    Description: A 3-line character LCD with an RGB backlight and joystick
    Manufacturer: Pimoroni
    Github: https://github.com/pimoroni/dot3k
    Url: https://github.com/pimoroni/dot3k

Install data found. Installing...
Checking for apt packages...
    python-smbus: Not found!
    python3-smbus: Not found!
    python-dev: Not found!
    python3-dev: Found!
    python-pip: Found!

Installing apt packages...
    sudo apt-get --force-yes --yes install python-smbus python3-smbus python-dev
    Successfully installed: python-smbus
    Successfully installed: python3-smbus
    Successfully installed: python-dev

Checking for Python 2 packages...
    dot3k: Not found! Will install.

Installing Python 2 packages...
    sudo pip2 install  dot3k
    Successfully installed dot3k

Installing examples from https://github.com/pimoroni/dot3k
    Find examples in ~/Pimoroni/dot3k

Done!

**Comment by Gadgetoid** [comment]
I'm guessing it's because I missed the "sudo apt-get update" step- I've been looking for a way to detect when it was last updated so I can determine if an update is really necessary since it takes a loonnng time. It's a pain- the sources change and things get moved about so even if packages are available apt may just hit broken URLs. I need to try and make that happen and find out what string to sniff to report it- then maybe it can do a retrospective update and retry the install.

**Comment by RogueM** [comment]
I ran it a few hours before so don't think that is it. I will try again later.

**Comment by Gadgetoid** [comment]
D'oh! Well it was a good guess. I'll tweak the script at some point to output all the command results to a debug log. Should make it  much easier to diagnose.

**Comment by RogueM** [comment]
actually, I've just tried again and it worked. Could be a temperamental network at the time!

**Comment by RogueM** [comment]
-- reinstall failed though (without details), but I'll close this issue for now and go back to it next week.

**Comment by lurch** [comment]
> I've been looking for a way to detect when it was last updated so I can determine if an update is really necessary since it takes a loonnng time.

Looks like e.g. `wget -q -O /dev/null -S http://archive.raspberrypi.org/debian/dists/jessie/Contents-armhf.gz 2>&1 | grep Last-Modified:` (or swap `jessie` with `wheezy` as necessary) will get you the last time the remote repo was updated (which I guess you'd need to do for all the repos in `/etc/apt/`), and `ls -l /var/cache/apt/pkgcache.bin` (which I've only checked on Ubuntu, not on Raspbian) will give you the last time that `sudo apt-get update` was run :-)
